name: recipe_recorder_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.2.1
  flutter_localizations:
    sdk: flutter

  intl: any
  flutter_slidable: ^4.0.0
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  intl_utils: ^2.8.0
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
