// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABRad9_X-q5THD7gNXVoKV3rNG0iqTjJM',
    appId: '1:929762269873:web:e5d1ade4192d763a746090',
    messagingSenderId: '929762269873',
    projectId: 'recipe-recorder-app',
    authDomain: 'recipe-recorder-app.firebaseapp.com',
    storageBucket: 'recipe-recorder-app.firebasestorage.app',
    measurementId: 'G-RWNJ4G2J2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-MZq2fly7DURtN9lTxSiNCTJnAh-V1QM',
    appId: '1:929762269873:android:2524f4ae2cd73ff2746090',
    messagingSenderId: '929762269873',
    projectId: 'recipe-recorder-app',
    storageBucket: 'recipe-recorder-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrjbRfxrXJVCg04tb_bjqKg9EHxRtvQX0',
    appId: '1:929762269873:ios:83c3f000d285cd8c746090',
    messagingSenderId: '929762269873',
    projectId: 'recipe-recorder-app',
    storageBucket: 'recipe-recorder-app.firebasestorage.app',
    iosBundleId: 'com.example.recipeRecorderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrjbRfxrXJVCg04tb_bjqKg9EHxRtvQX0',
    appId: '1:929762269873:ios:83c3f000d285cd8c746090',
    messagingSenderId: '929762269873',
    projectId: 'recipe-recorder-app',
    storageBucket: 'recipe-recorder-app.firebasestorage.app',
    iosBundleId: 'com.example.recipeRecorderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABRad9_X-q5THD7gNXVoKV3rNG0iqTjJM',
    appId: '1:929762269873:web:b905da2a1033ca6c746090',
    messagingSenderId: '929762269873',
    projectId: 'recipe-recorder-app',
    authDomain: 'recipe-recorder-app.firebaseapp.com',
    storageBucket: 'recipe-recorder-app.firebasestorage.app',
    measurementId: 'G-TMHCS0KQ7Z',
  );
}
